version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=74.235.82.175'
        volumes:
          - ./app:/app
        ports:
            - 8001:8001